# ====================================== AIRFLOW ENVIRONMENT VARIABLES =======================================
x-environment: &airflow_environment
  - AIRFLOW__CORE__EXECUTOR=LocalExecutor
  - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
  - AIRFLOW__CORE__LOAD_EXAMPLES=False
  - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://airflow:airflow@postgres:5432/airflow
  - AIRFLOW__CORE__STORE_DAG_CODE=True
  - AIRFLOW__CORE__STORE_SERIALIZED_DAGS=True
  - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
  - AIRFLOW__WEBSERVER__RBAC=False
  # Email configuration for MailHog
  - AIRFLOW__SMTP__SMTP_HOST=mailhog
  - AIRFLOW__SMTP__SMTP_PORT=1025
  - AIRFLOW__SMTP__SMTP_USER=
  - AIRFLOW__SMTP__SMTP_PASSWORD=
  - AIRFLOW__SMTP__SMTP_MAIL_FROM=airflow@example.com
  - AIRFLOW__SMTP__SMTP_STARTTLS=False
  - AIRFLOW__SMTP__SMTP_SSL=False
x-airflow-image: &airflow_image apache/airflow:2.5.0-python3.8
# ====================================== /AIRFLOW ENVIRONMENT VARIABLES ======================================
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
  init:
    image: *airflow_image
    depends_on:
      - postgres
    environment: *airflow_environment
    entrypoint: /bin/bash
    command: -c 'pip install pandas openpyxl && airflow db upgrade && sleep 5 && airflow users create --username admin --password admin --firstname Anonymous --lastname Admin --role Admin --email admin@example.org'
  webserver:
    image: *airflow_image
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - logs:/opt/airflow/logs
      - ./dags:/opt/airflow/dags
      - ./dags/data:/opt/airflow/dags/data
    environment: *airflow_environment
    entrypoint: /bin/bash
    command: -c 'pip install pandas openpyxl && airflow webserver'
  scheduler:
    image: *airflow_image
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - logs:/opt/airflow/logs
      - ./dags/data:/opt/airflow/dags/data
    environment: *airflow_environment
    entrypoint: /bin/bash
    command: -c 'pip install pandas openpyxl && airflow scheduler'

  # MailHog for email testing
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    restart: always

volumes:
  logs:
